export default {
    EN: {
    },
    ID: {
        BUTTON_LOGIN: 'Masuk',
        BUTTON_SAVE: 'Simpan',
        BUTTON_CANCEL: 'Batal',
        BUTTON_CHARGE: 'Proses Belanjaan',
        BUTTON_EDIT_CUSTOMER_DATA: 'Ubah Data Pelanggan',
        BUTTON_SAVE_CUSTOMER: 'Tambahkan Pelanggan',
        BUTTON_ADD: 'Tambahkan',
        BUTTON_DETAIL: 'Detail',
        BUTTON_CLEAR: 'Hapus',
        BUTTON_SAVE_ADDRESS: 'Simpan Alamat',
        BUTTON_CART_ADD: "Tambah ",
        BUTTON_SELECT_CUSTOMER: "Pilih",
        BUTTON_SAVE_ORDER: "Proses Belanjaan",
        BUTTON_SAVE_PAYMENT: "Proses Pembayaran",
        BUTTON_YES_DELETE: "Ya,hapus",
        BUTTON_RELOGIN: "Login",
        BUTTON_BACK: "Kembali",
        BUTTON_EDIT_CUSTOMER: "Ubah",
        LABEL_RETRY_CONNECTION:"Coba lagi",
        CALENDAR_TITLE_TEXT: "Pilih Tanggal Filter",
        CALENDAR_TITLE_FROM_DATE: "Tanggal mulai",
        CALENDAR_TITLE_TO_DATE: "Tanggal sampai",
        CALENDAR_TITLE_DELIVERY_DATE: "Tanggal pengiriman",
        NOTIFICATION_INVALID_TOKEN_TITLE: "Login Tidak Valid",
        NOTIFICATION_INVALID_TOKEN_DESC: "Akun ini sedang login pada perangkat lain, harap lakukan login kembali",
        HEADER_CHOOSE_CATEGORY: "Pilih kategori",
        HEADER_CHOOSE_PRODUCT: "Pilih produk",
        TEXT_TITLE_DESC: "Selamat datang di Sistem POS",
        TEXT_DESCRIPTION: "Majukan bisnis Anda dengan bantuan sistem pengelolaan penjualan dan transaksi secara online dengan aplikasi yang memiliki tampilan intuitif untuk meningkatkan efisiensi dalam melakukan transaksi dengan pelanggan.",
        TEXT_INVOICE_NUMBER: 'Nomor Invoice',
        NO_INTERNET_TITLE:"Jaringan tidak stabil",
        NO_INTERNET_DESC:"Tidak dapat mengambil data pada server dikarenakan jaringan tidak tersedia",
        NO_INTERNET_DETECTED:"Jaringan tidak stabil, harap dilakukan pengecekan",
        ON_DELIVERY_TITLE:"Sudah terkirim",
        ON_DELIVERY_DESC:"Pengiriman barang untuk penjualan ini sudah dikirimkan",
        IS_PAID_TITLE:"Sudah dibayar",
        IS_PAID_DESC:"Pembayaran untuk penjualan ini sudah lunas dibayarkan",
        TOAST_WARNING_ERROR_SERVER:"Terjadi kesalahan pada server",
    }
}